### PR TITLE
config: Update config-tool to v0.1.11 (PROJQUAY-3318)

### PR DESCRIPTION
**Pull request by jonathankingfc**
- Update config-tool version from v0.1.10 to v0.1.11

### CODE REVIEW

**Comment by ricardomaraschini** [comment]
@HammerMeetNail this one addresses two blocker bugs. As @jonathankingfc ended closing the Jira cards can you prioritize the review of this one ? I think we also need to update the "midstream", can you confirm ?

**Review by bcaton85 — APPROVED** [review]
LGTM

**Comment by HammerMeetNail** [comment]
> @HammerMeetNail this one addresses two blocker bugs. As @jonathankingfc ended closing the Jira cards can you prioritize the review of this one ? I think we also need to update the "midstream", can you confirm ?

I don't think we need to update the midstream for config-tool. I don't see anything that jumps out at me in the midstream Dockerfile for config-tool. @flavianmissi @harishsurf Can either of you confirm?

**Comment by flavianmissi** [comment]
AFAIK as long as the config-tool commit makes it into the equivalent redhat branch the commit will be included in the next downstream build.

**Pull request merged**
