### PR TITLE
Update storage to boto3

### PR DESCRIPTION
**Pull request by kleesc**
### Description of Changes

* Migrate storage from boto2 to boto3

#### Issues: 
- https://issues.redhat.com/browse/PROJQUAY-835
- https://issues.redhat.com/browse/PROJQUAY-922

**TESTING** ->

**BREAKING CHANGE** ->

---

## Reviewer Checklist

- [ ] It works!
- [ ] Comments provide sufficient explanations for the next contributor
- [ ] Tests cover changes and corner cases
- [ ] Follows Quay syntax patterns and format

### CODE REVIEW

**Comment by kleesc** [comment]
Ping @thomasmckay @alecmerdler @jonathankingfc

**Review by thomasmckay — APPROVED** [review]
LGTM

**Review by thomasmckay — DISMISSED** [review]
LGTM

**Review by thomasmckay — APPROVED** [review]
LGTM

**Pull request merged**
