### PR TITLE
Renamed FEATURE_EXPERIMENTAL_HELM_OCI_SUPPORT feature flag

### PR DESCRIPTION
**Pull request by BillDett**
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1142
Removed 'EXPERIMENTAL' from Helm V3 feature flag name.

**Changelog:** 

**Docs:** 
As referenced in 3.4 release notes.

**Testing:** 

**Details:**

### CODE REVIEW

**Review by alecmerdler — CHANGES_REQUESTED** [review]
This means anyone who was using this config field before will need to update their `config.yaml` to use the new key to continue using this feature. Is that acceptable?

**Comment by thomasmckay** [comment]
@jonathankingfc When config schema changes, is there anything that is required in config-tool?

**Comment by BillDett** [comment]
@alecmerdler - I think it would be acceptable.  if the feature is no longer experimental then the flag name would be misleading.  Only tire-kickers should be using it while it's experimental so I think asking them to update config isn't unreasonable.

**Review by thomasmckay — APPROVED** [review]
LGTM

**Review by BillDett — COMMENTED** [review]
@alecmerdler - any further concerns here over merging this?

**Review by alecmerdler — APPROVED** [review]

**Pull request merged**
