### PR TITLE
Add better tagging options for build triggers.

### PR DESCRIPTION
**Pull request by josephschorr**
Users can now configure whether they want the default tagging options enabled (tag `latest` for the default branch, and tag with the git branch or tag name), and can also specify custom tags, including static tags and dynamic templated tags.

Fixes https://jira.coreos.com/browse/QUAY-1747

### CODE REVIEW

**Comment by josephschorr** [comment]
@dongboyan77 Can you verify?

**Comment by dongboyan77** [comment]
Test with github build trigger, could add custom tag.
Screenshot from 2020-01-19 11-14-05

But failed to add custom tag for custom git build trigger
Screenshot from 2020-01-17 15-25-15

**Comment by josephschorr** [comment]
@dongboyan77 How did you test the custom git and see its tagging fail? Typically, custom git gets its tags from the webhook itself

**Comment by dongboyan77** [comment]
@josephschorr I add custom tag in above web console page for custom git build trigger,
So you mean we can add tags from webhook for custom git without this PR, right?

**Comment by josephschorr** [comment]
@dongboyan77 Yeah. I'll see if I can extend this PR to support it here as well.

**Comment by josephschorr** [comment]
@dongboyan77 Fixed. please try again

**Comment by dongboyan77** [comment]
Add custom tag for custom git build trigger via webconsole successfully
Screenshot from 2020-02-04 14-06-05

**Pull request merged**
