### PR TITLE
task: Temporary remove s390x support (PROJQUAY-7673)

### PR DESCRIPTION
**Pull request by modassarrana89**
Removed s390x changes temporarily . 
Updating s390x instance with sudo user & same will be updated in this workflow

### CODE REVIEW

**Comment by modassarrana89** [comment]
@ibazulic Please review & approve the changes . I have stopped s390x instance (  to fix CVE issue ) , so build and publish workflow will be imapacted. Thats why i am removing s390x changes temporarily & will revert back the change post the issue is fixed

**Review by ibazulic — APPROVED** [review]

**Review by ibazulic — CHANGES_REQUESTED** [review]
Can you please fix linting before we merge this? Thanks!

**Comment by modassarrana89** [comment]
> @modassarrana89 Can you please fix linting before we merge this? Thanks!

@ibazulic Lint is for PR Title . It's not relevant to the commit. Do you  still want me to update it . Then i will do the same . else please merge the changes

**Comment by ibazulic** [comment]
@modassarrana89 precommit checks are failing because of wrong indentation and white spaces. 

https://github.com/quay/quay/actions/runs/10382241432/job/28744977477?pr=3140

Can you please fix this so we can merge? Thank you!

**Review by ibazulic — APPROVED** [review]
@modassarrana89 Approved, but pre-commit checks are still failing, due to issues with indentation. JIRA has been created for future tracking.

**Pull request merged**
