### PR TITLE
requirements-osbs.txt: Add missing deps for Cachito (PROJQUAY-3177)

### PR DESCRIPTION
**Pull request by HammerMeetNail**
* Adds previously removed but required downstream dependencies

### CODE REVIEW

**Comment by flavianmissi** [comment]
I _think_ version `1.0.0a0` of `funcparserlib` isn't present in cachito, and that's why it differs from `requirements.txt`. @harishsurf do you happen to remember this?
Would be nice if we could check whether a library version is present in cachito, I don't know if that's possible 🤔

**Review by flavianmissi — APPROVED** [review]
Giving the green light - let's keep an eye downstream in case `1.0.0a0` isn't around.

**Comment by flavianmissi** [comment]
TIL!

**Review by flavianmissi — APPROVED** [review]

**Comment by HammerMeetNail** [comment]
@flavianmissi Updated the PR based on the latest passing build. Needed to restore a few deps that were recently removed. They're dependencies of other dependencies.

**Review by flavianmissi — APPROVED** [review]
Thanks for fixing @HammerMeetNail ! LGTM

**Pull request merged**
