### PR TITLE
Remove the active migration for encrypted tokens now that it is complete

### PR DESCRIPTION
**Pull request by josephschorr**
Fixes https://issues.redhat.com/browse/PROJQUAY-185

### CODE REVIEW

**Comment by josephschorr** [comment]
@thomasmckay Done

**Comment by josephschorr** [comment]
@thomasmckay Yes, as data/migrationutil.py is the framework for defining migrations. This PR removes the currently active migration, but it leaves the framework in place for future data migrations as needed. Note that the code won't be called right now since `ActiveMigration` is `None` as of this PR.

**Comment by kurtismullins** [comment]
@josephschorr Just a heads-up, it looks like there are test failures.

**Comment by josephschorr** [comment]
@kurtismullins updated

**Pull request merged**
