### PR TITLE
format: Updating black to resolve click dependency issue (PROJQUAY-3487)

### PR DESCRIPTION
**Pull request by bcaton85**
Currently the CI breaks due to a dependency of black, `click`, breaking with it's latest release with `ImportError: cannot import name '_unicodefun' from 'click'`. Since black does not pin it's version of click it pulls in the latest version containing the breaking change, it fails the CI check. This updates black with the patch. [See the original issue here.](https://github.com/psf/black/issues/2964)

### CODE REVIEW

**Comment by HammerMeetNail** [comment]
All of the file changes are related to running black?

**Comment by bcaton85** [comment]
The updated version of black requires different formatting. The rest of the changes are formatting differences required for black, mostly adding/removing whitespace.

**Review by HammerMeetNail — APPROVED** [review]
LGTM 👍

**Pull request merged**
