### PR TITLE
users: add restricted users' filter (PROJQUAY-1245)

### PR DESCRIPTION
**Pull request by kleesc**
Similar to LDAP_SUPERUSER_FILTER, add a specific filter to define
    restricted users, based on the LDAP_USER_FILTER
    - restrict writes on restricted users' own namespace. Normal
    permissions applies on organization membership
    - add global readonly superuser GLOBAL_READONLY_SUPER_USERS (PROJQUAY-2604)
    - Removes RESTRICTED_USER_INCLUDE_ROBOTS, FEATURE_RESTRICTED_READ_ONLY_USERS

### CODE REVIEW

**Comment by HammerMeetNail** [comment]
LGTM, waiting on @bcaton85 to approve too

**Review by HammerMeetNail — APPROVED** [review]

**Review by bcaton85 — APPROVED** [review]
LGTM
Tested pulling image as global readonly superuser and pushing an image to the user namespace as a restricted user. Both worked as expected.

**Pull request merged**
