### PR TITLE
chore: Remove Docker Build jobs (PROJQUAY-5519)

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by bcaton85** [comment]
Is there any negative impact to removing these tests? I suppose we would know about it at some point. Also shouldn't `Docker Build` be in the CI tests for this PR?

**Comment by dmage** [comment]
@bcaton85 `Docker Build` will be replaced by `Cypress Tests`, once this PR is merged - `Cypress Tests` will become required, and `Docker Build amd64` will be removed completely.

amd64 builds are verified twice anyway - by OCI Distribution tests and by Cypress tests.
Other platforms will be verified by the post-merge job that build `3.9-unstable` for amd64/arm64/s390x/ppc64le.

**Review by bcaton85 — APPROVED** [review]
LGTM

**Comment by dmage** [comment]
Negative impact - we can accidentally break arm64/s390x/ppc64le, and we'll know about it only after the change is merged. Good thing - we'll be able to use our own builders, so these builds should become more reliable.

**Pull request merged**
