### PR TITLE
chore: Use GitHub Actions cache for Docker Build jobs (PROJQUAY-4970)

### PR DESCRIPTION
**Pull request by dmage**
It takes >2 hours to build a Quay image for linux/arm64 by GitHub Actions. Caching should help us speed things up a bit.

### CODE REVIEW

**Comment by dmage** [comment]
It also should help us with `npm install` failures on arm64 as its results often can be taken from cache.

**Comment by syed** [comment]
@dmage there's also `Dockerfile.static` does that need to be updated as well?

**Comment by dmage** [comment]
@syed I cannot find Dockerfile.static, perhaps it was deleted?

**Comment by syed** [comment]
sorry the other file was `Dockerfile.dev` not sure if we need that anymore. If not, we should remove it, keep only one Dockerfile

**Comment by dmage** [comment]
I see only one Dockerfile in the repo.

**Review by syed — APPROVED** [review]
LGTM

**Pull request merged**
