### PR TITLE
secscan_model: attempt urldecoding `fixed_in_version` (PROJQUAY-5886)

### PR DESCRIPTION
**Pull request by hdonnay**
In Clair 4.7, an API field documented to have version information in no particular format may URL encode it. This change attempts to decode and read a known field that contains the "fixed" version. If that fails, the value will be passed through, as it is now.

Closes: [PROJQUAY-5886](https://issues.redhat.com//browse/PROJQUAY-5886)

### CODE REVIEW

**Review by crozzy — COMMENTED** [review]
LGTM, but I'll leave the approval to @kleesc, I assume the import deletions were due to your editor settings?

**Comment by hdonnay** [comment]
> LGTM, but I'll leave the approval to @kleesc[.]

Yeah, I wanted to have you double-check the shape of the url decoded dict is correct.

>I assume the import deletions were due to your editor settings?

Yeah, must have been.

**Comment by hdonnay** [comment]
The "conventional commit" check doesn't like the underscore, but that's the name of the python module, so :shrug:. Can change it to whatever as needed.

**Review by kleesc — APPROVED** [review]
lgtm

**Comment by Sunandadadi** [comment]
@HammerMeetNail here is the pull request on 3.8 branch - https://github.com/quay/quay/pull/2066

**Pull request merged**
