### PR TITLE
PROJQUAY-28 - 'black' python format

### PR DESCRIPTION
**Pull request by thomasmckay**
To run: make black

line length 100
target version py27

https://issues.jboss.org/browse/PROJQUAY-28

### CODE REVIEW

**Comment by thomasmckay** [comment]
@cclauss - FYI - Working through the inevitable debates and changes required for this change. Your earlier PR very much appreciated.

**Comment by cclauss** [comment]
You might look at a GitHub Action that I created called __autoblack__ as demoed in https://github.com/TheAlgorithms/Python/actions?query=workflow%3Aautoblack_push The code for the Action is https://github.com/TheAlgorithms/Python/blob/master/.github/workflows/autoblack.yml and its job is to reformat Python code with __black__ on all __push__ commands.  This adds a new commit to the PR that re-blackens the code so that reviewer never need to review unblackend code.

**Comment by thomasmckay** [comment]
@cclauss The consensus was to prefer contributors format their code appropriately. If this becomes problematic we can revisit.

**Comment by kurtismullins** [comment]
@thomasmckay 

Just a heads up, Github is reporting conflicts against HEAD that need to be resolved.

**Comment by cclauss** [comment]
@kurtismullins As discussed at https://github.com/quay/quay/pull/27#issuecomment-557544776

**Comment by thomasmckay** [comment]
After this is merged we'll enable the auto-fix workflow as @cclauss suggested.

**Pull request merged**
