### PR TITLE
chore: Upgrade to black 20.8b1 for Python style check (PROJQUAY-1021)

### PR DESCRIPTION
**Pull request by arajkumar**
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1021

**Details:** 

Upgrade black to use 20.8b1 version which is latest.

### CODE REVIEW

**Review by kurtismullins — COMMENTED** [review]
Hey @arajkumar, is this still using a line length of 100? The pull request appears to have affected quite a few files.

**Comment by arajkumar** [comment]
@kurtismullins There is no change in the black config, looks like there was change in latest black which affects formatting.

A workaround to use the previously working version got already merged #536 .

**Comment by kurtismullins** [comment]
@arajkumar We're currently working on a release candidate. Once it's finished, do you mind to rebase your changes and we can get your PR merged? 

Thank you for doing this! This has been encountered quite a few times now by various developers.

**Comment by thomasmckay** [comment]
thanks @arajkumar for this! i had @kurtismullins create a fresh PR for this due to timeliness of making the downstream branch
https://github.com/quay/quay/pull/607

**Comment by HammerMeetNail** [comment]
Superseded by https://github.com/quay/quay/pull/607

**Pull request closed without merging**
