### PR TITLE
secscan: Generate key to reduce vulnerabilities (PROJQUAY-4562)

### PR DESCRIPTION
**Pull request by crozzy**
Currently Quay is displaying the Clair response with no interpretation meaning when Clair reports on vulns per repo they appear to be duplicated (RHEL based images with multiple repos and packages existing in more than one). The correct way to fix this is via an interpretation layer in Quay, this change is a stop-gap to improve readability for the user.

Signed-off-by: crozzy <joseph.crosland@gmail.com>

### CODE REVIEW

**Comment by crozzy** [comment]
Before:
image


After:
image

**Comment by crozzy** [comment]
It'd probably be good to review the key and if it's potentially over-eagar

**Review by kleesc — APPROVED** [review]
LGTM

**Pull request merged**
