### PR TITLE
Update NodeJS version

### PR DESCRIPTION
**Pull request by ibazulic**
This PR updates NodeJS version to 12, since 8 (old LTS) is no longer supported. It also adds additional packages to `package.json` file that were creating warnings on previous builds.

#### Changes:

* updated `˙package.json` file
* updated Dockerfile to include NodeJS 12 instead of 8

### CODE REVIEW

**Comment by kurtismullins** [comment]
@IvanCherepov Do you mind to drop this down to NodeJS v1.10 as that's the version available in RHEL8?

**Comment by kurtismullins** [comment]
@ibazulic Just a heads-up -- I have created an associated Jira and edited your PR's description to include a link to it.

**Comment by kurtismullins** [comment]
@thomasmckay Does this change also need to be applied to the other Dockerfiles? Specifically, the Dockerfile used for Redhat builds?

**Comment by thomasmckay** [comment]
@kurtismullins yes, this change should be made to Dockerfile.rhel7 as well.

**Pull request merged**
