### PR TITLE
api: Duplicate Robot accounts (PROJQUAY-5931)

### PR DESCRIPTION
**Pull request by Sunandadadi**
The tuples returned [here](https://github.com/quay/quay/blob/master/endpoints/api/robot_models_pre_oci.py#L37) were not distinct. So, in the for loop, if a robot_name already exists in the `robots` dictionary as [here](https://github.com/quay/quay/blob/master/endpoints/api/robot_models_pre_oci.py#L45) , the `robot_dict` is not constructed and previous items `robot_dict` is used for the current robots[robot_name]. So, the current robot_name is overwritten by previously constructed robot_dict.

By using distinct set of items, we won't run into the above issue.

### CODE REVIEW

**Review by ibazulic — APPROVED** [review]
Can't reproduce the issue. LGTM!

**Comment by bcaton85** [comment]
Okay I see the issue. The [loop through the permissions](https://github.com/quay/quay/blob/master/endpoints/api/robot_models_pre_oci.py#L43) returned expects the list to be ordered by username but it is instead ordered by last accessed, and when that is null an entry with the same username can appear in different parts of the list. 

The issue is that [this loop](https://github.com/quay/quay/blob/master/endpoints/api/robot_models_pre_oci.py#L43) only updates [the robot_dict](https://github.com/quay/quay/blob/master/endpoints/api/robot_models_pre_oci.py#L45-L70) info when it encounters a robot name it hasn't seen before. So if the same robot name appears twice in different places in the list, `robot_dict` doesn't get updated and you assign robot permissions to the wrong robot. 

`distinct` works because it forces the list to be ordered by username. But i'm wary on using it since `distinct` as some performance costs. IMO having the code rely on this odd scoping mechanism should be refactored and fixed and that would prevent the need to modify any DB calls. Or at change the ordering to be by username. @kleesc what are your thoughts?

**Comment by kleesc** [comment]
Was this intentional before, or just was never caught?
Like @bcaton85 mentioned, there's probably _some_ performance tradeoffs of using `distinct` (to what extent I'm not sure of, but it's probably not _that_ significant for this specific use case). You could also do the union of the tuples at the application layer instead of changing the db query.

**Comment by Sunandadadi** [comment]
Was running into some issues with git so had to close this. Opened the fix here - https://github.com/quay/quay/pull/2192 instead

**Pull request closed without merging**
