### PR TITLE
chore: Use Python 3.9

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Review by flavianmissi — COMMENTED** [review]
this looks great!
how about updating the required python version on our getting started docs as well? https://github.com/quay/quay/blob/master/docs/getting-started.md#requirements

**Review by flavianmissi — APPROVED** [review]
LGTM 🚀

**Comment by HammerMeetNail** [comment]
Did the base64 decodestring import get fixed? I think that was removed in python 3.9

**Comment by dmage** [comment]
`elasticsearch==7.6.0` doesn't use decodestring anymore.

**Pull request merged**
