### PR TITLE
[wip] Return 201 on application creation

### PR DESCRIPTION
**Pull request by jharmison-redhat**
### Description of Changes

* On application creation via API, return a 201 response
* Documentation and convention reflect that a 201 should be returned when a resource is created
* Previously, a 200 was returned
* I do not know what changes would be required, if any, in the JS for the front-end to reflect this change.
* If you think there should be a regression test, I can dig into your tests to implement it if you would like. I have, admittedly, not looked at it at all.

#### Changes:

* Application creation now returns a 201 HTTP response code via the API

#### Issue: https://issues.redhat.com/browse/PROJQUAY-726

**TESTING** ->

**BREAKING CHANGE** ->

---

## Reviewer Checklist

- [ ] It works!
- [ ] Comments provide sufficient explanations for the next contributor
- [ ] Tests cover changes and corner cases
- [ ] Follows Quay syntax patterns and format

### CODE REVIEW

**Comment by jharmison-redhat** [comment]
I'll be adding some more to this and running tests locally before push next time, I suppose.

**Comment by jharmison-redhat** [comment]
As the issue has been assigned on the tracker and I don't have the cycles I thought I would to help address this, I'm closing this small, incomplete PR.

**Comment by alecmerdler** [comment]
@jharmison-redhat Hey, just to let you know, our team assigns community contribution issues to one of the team members to ensure that it gets the attention that it needs to get resolved. 

I'm happy to help with this PR; it looks like you just need to update the tests. If you are strained for time, do you want me to take over this branch and add commits to fix?

**Comment by jharmison-redhat** [comment]
I am strained for time, and am unfamiliar with the project layout. I imagine that there's more than just tests to finish, though, as I'd expect the front end to expect a certain response as well - which is the area I'm even less familiar with.

I know some Python, but haven't dug into how your tests are structured and know very little JS :)

If you want to take it over feel free - if you'd rather wait until I have some cycles it would likely be weeks. I apologize, but I've just worked around this for now with the project that surfaced the issue for me.

**Pull request closed without merging**
