### PR TITLE
api: adding endpoints to FEATURE_SUPERUSERS_FULL_ACCESS (PROJQUAY-7045)

### PR DESCRIPTION
**Pull request by bcaton85**
Allows superuser to have access to additional endpoints when the `FEATURE_SUPERUSERS_FULL_ACCESS` flag is enabled.

### CODE REVIEW

**Comment by bcaton85** [comment]
It's because i added a repo under `freshuser` and `test_noaccess` expected `freshuser` to have none.

**Review by ibazulic — DISMISSED** [review]

**Comment by bcaton85** [comment]
Yes, I'll do that

**Review by kleesc — DISMISSED** [review]
LGTM

**Review by kleesc — APPROVED** [review]

**Pull request merged**
